# <center>Crash course 1: Vectors and matrices in numpy and scipy</center>
### <center>Alfred Galichon (NYU & Sciences Po)</center>
## <center>'math+econ+code' masterclass on optimal transport and economic applications</center>
<center>© 2018-2022 by Alfred Galichon. Past and present support from NSF grant DMS-1716489, ERC grant CoG-866274, and contributions by Jules Baudet, Pauline Corblet, Gregory Dannay, and James Nesbit are acknowledged.</center>

#### <center>With python code examples</center>

# Introducing NumPy

* Unlike R or Matlab, Python has no built-in matrix algebra interface. Fortunately, the NumPy library provides powerful matrix capabilities, on par with R or Matlab. Here is a quick introduction to vectorization, operations on vectors and matrices, higher-dimensional arrays, Kronecker products and sparse matrices, etc. in numpy.

* This is *not* a tutorial on Python itself. They are plenty good ones available on the web.

* First, we load numpy:

In [2]:
import numpy as np

## Vectorization

We will need to represent matrices (such as $U_{x}^{t}$) and 3-dimensional arrays (such as $u_{xy}^{t}$). Under the row-major order (a.k.a. 'C order') used in `C` and by default in `numpy`, we will represent a matrix $M_{ij}$ by varying the last index first, i.e. a $2\times2$ matrix will be represented as $vec_C\left(M\right) = M_{11}, M_{12}, M_{21}, M_{22}.$ Likewise, a 2x2x2 3-dimensional array $A$ will be represented by varying the first index first, then the second, i.e.

$vec_C\left(A\right) = A_{111}, A_{112}, A_{121}, A_{122}, A_{211}, A_{212}, A_{221}, A_{222}$.

In `numpy`, this is implemented by `reshape(...)`.



## Vectorization and memory order

* Matrices in all mathematical softwares are represented in a *vectorized* way as a sequence of numbers in the computers memory. This representation can involve either stacking the lines, or stacking the columns.

* Different programming languages can use either of the two stacking conventions:
    + Stacking the lines (Row-major order) is used by C, and is the default convention for for Python (Numpy).
    + Stacking the columns (Column-major order) is used by Fortran, Matlab, R, and most underlying core linear algebra libraries (like BLAS). A $2\times2$ matrix $A$ is then vectorized as $\left(  A_{11},A_{21},A_{12},A_{22}\right)$. Thus, we shall remember that R represents matrices by **varying the first index first**.

In [2]:
a = np.array([[11,12],[21,22],[31,32]])
a

array([[11, 12],
       [21, 22],
       [31, 32]])

In [3]:
a.shape

(3, 2)

In order to reshape the vector matrix `a`, one modifies its `shape` attribute. The following reshapes the matrix `a` into a row vector. 

In [4]:
a.shape = 1,6
a

array([[11, 12, 21, 22, 31, 32]])

The previous output evidences the fact that Python uses the row-major order: rows are stacked one after the other. 
To reshape the vector into a column vector, do:

In [5]:
a.shape = 6,1
a

array([[11],
       [12],
       [21],
       [22],
       [31],
       [32]])

Equivalently, one could have set `tst.shape=6,-1`, where Python would replace `-1` in `tst.shape=1,-1` by the integer needed for the formula to make sense (in this case, `1`). 
Another way to reshape is to use the method `reshape,` which returns a duplicate of the object with the requested shape.

In [6]:
a1=np.array(range(6))
a2 = a1.reshape(3,2)
print(a1)
print(a2)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


Note that numPy also supports the column-major order, but you have to specifically ask for it, by passing the optional argument `order='F'`, where 'F' for Fortran.

In [7]:
a3 = np.array(range(6)).reshape(3,2, order='F')
a3

array([[0, 3],
       [1, 4],
       [2, 5]])

## Kronecker product

A very important identity is
\begin{align*}
vec_C\left(AXB\right) = \left(  A\otimes B^\top\right)  vec_C\left(X\right),
\end{align*}
where $vec_C$ is the vectorization under the C (row-major) order, and where the Kronecker product $\otimes$ is defined as follows for 2x2 matrices (with obvious generalization):

\begin{align*}
A\otimes B=
\begin{pmatrix}
a_{11}B & a_{12}B\\
a_{21}B & a_{22}B
\end{pmatrix}.
\end{align*}



## Type broadcasting in numpy


In [9]:
a = 10*np.array([[1],[2],[3]])
b =  np.array([1,2])
print(a)
print(b)
print(a+b)

[[10]
 [20]
 [30]]
[1 2]
[[11 12]
 [21 22]
 [31 32]]


# Sparses matrices in Scipy

Sparse matrices are available in the `sparse` module of the `scipy` library. 

In [11]:
import scipy.sparse as spr

In [60]:
n = 1000

print('size of sparse identity matrix of size '+str(n) +' in MB = ' + str(spr.identity(n).data.size  / (1024**2)))

print('size of dense identity matrix of size '+str(n) +' in MB  = ' + str(spr.identity(n).todense().nbytes  / (1024**2)))

size of sparse identity matrix of size 1000 in MB = 0.00095367431640625
size of dense identity matrix of size 1000 in MB  = 7.62939453125


In [46]:
spr.identity(1000).data.size  , spr.identity(1000).todense().nbytes 

(1000, 8000000)

In [13]:
I5 = spr.identity(5)
I5

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements (1 diagonals) in DIAgonal format>

In [15]:
I5.todense()

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
I5 + np.ones((5,5))

matrix([[2., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1.],
        [1., 1., 2., 1., 1.],
        [1., 1., 1., 2., 1.],
        [1., 1., 1., 1., 2.]])

In [18]:
I5 + np.diag([1.,2.,3.,4.,5.])

matrix([[2., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0.],
        [0., 0., 4., 0., 0.],
        [0., 0., 0., 5., 0.],
        [0., 0., 0., 0., 6.]])

In [20]:
I5 @ np.diag([1.,2.,3.,4.,5.])

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [32]:
kron_product = spr.kron(I5 , 10 *np.array([[1,2],[3,4]]))

In [33]:
kron_product.todense()

matrix([[10., 20.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [30., 40.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0., 10., 20.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0., 30., 40.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., 10., 20.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., 30., 40.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0., 10., 20.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0., 30., 40.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 20.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 30., 40.]])